default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  SECRET_KEY: ""
  SITE_ID: 0
  TIME_ZONE: ""
  DEBUG: true
  API_KEY: ""
  MODE_CACHING: false
  MODE_DEBUG: false
  MODE_PROFILING: false

development:
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"
  DEBUG: true
  MODE_CACHING: 0
  MODE_DEBUG: 1
  MODE_PROFILING: 0

docker:
  DATABASE_URL: "postgresql://anastasiyataranava:1@task-manager-db:5432/tasks"
  MODE_CACHING: 0
  MODE_DEBUG: 0
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"

test:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"
  DEBUG: true
